export const qk = {
  session: ["session"] as const,
  dashboard: ["dashboard"] as const,
  products: (search?: string) => ["products", search ?? ""] as const,
  product: (id: string) => ["product", id] as const,
  categories: ["categories"] as const,
  customers: (search?: string) => ["customers", search ?? ""] as const,
  customer: (id: string) => ["customer", id] as const,
  sales: (search?: string) => ["sales", search ?? ""] as const,
  sale: (id: string) => ["sale", id] as const,
  movements: ["movements"] as const,
  lowStock: ["lowStock"] as const,
  dailyReport: (date: string) => ["dailyReport", date] as const,
  salesReport: (period: string) => ["salesReport", period] as const,
  periodTotals: ["periodTotals"] as const,
  salesSeries: ["salesSeries"] as const,
  settings: ["settings"] as const,
  units: ["units"] as const,
  users: ["users"] as const,
};
